Shorten the number of required params

diff --git a/linux/oav-custom/compile b/linux/oav-custom/compile
--- a/linux/oav-custom/compile
+++ b/linux/oav-custom/compile
@@ -2,9 +2,9 @@
 
 set -e
 
-if [[ $# -ne 5 ]] ; then
+if [[ $# -ne 3 ]] ; then
     echo "Error: Invalid number of parameters"
-    echo "Correct usage: ./linux/oav-custom/$(basename "$0") <os_name> <flutter_arch> <bundle_arch> <deb_arch> <deb_depends>" >&2
+    echo "Correct usage: ./linux/oav-custom/$(basename "$0") <os_name> <flutter_arch> <deb_depends>" >&2
     exit 1
 fi
 
@@ -17,9 +17,19 @@ set -x
 
 export os_name="$1"
 export flutter_arch="$2"
-export bundle_arch="$3"
-export deb_arch="$4"
-export deb_depends="$5"
+export deb_depends="$3"
+
+if [[ $flutter_arch = x64 ]] ; then
+    deb_arch=amd64
+    bundle_arch=x86_64
+elif [[ $flutter_arch = arm64 ]] ; then
+    deb_arch=arm64
+    bundle_arch=aarch64
+else
+    echo "Invalid Flutter arch. Must be either 'x64' or 'arm64'." >&2
+    exit 1
+fi
+
 
 export PATH="$PATH:$(pwd)/.flutter/bin/"
 
@@ -27,6 +37,7 @@ export version="$(grep -e "^version: " < pubspec.yaml | sed -e "s/^version: //; 
 
 export bundle_name="oav-bundle-ubuntu-${os_name}-${bundle_arch}"
 export deb_dir=open-alert-viewer_"${version}"
+
 
 git submodule init
 git submodule update
