Complain if there are build files already present

diff --git a/linux/oav-custom/compile b/linux/oav-custom/compile
--- a/linux/oav-custom/compile
+++ b/linux/oav-custom/compile
@@ -48,6 +48,11 @@ export version="${version}-1${distro_name}${distro_release}"
 export bundle_name="oav-bundle-${distro_name}${distro_release}-${bundle_arch}"
 export deb_dir=open-alert-viewer_"${version}"
 
+if [[ -e ./${bundle_name} ]] ; then
+    echo "Error, build files are already present here." >&2
+    echo "Consider wiping the untracked files with: git clean -fxd" >&2
+    exit 1
+fi
 
 if [[ $use_flutter_git == true ]] ; then
     git submodule init
